---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    env_file:
      - wireguard.env
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - ${WIREGUARD_PORT:?err}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
